version: 0.2
phases:
  build:
    commands:
      - sudo apt-get update && sudo apt-get install -y gnupg software-properties-common apt-transport-https ca-certificates curl jq
      # Install aws-cli
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      # - unzip awscliv2.zip
      # - sudo ./aws/install
      # install terraform
      - wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt update && sudo apt install terraform
      # Get S3 Bucket
      - export TF_VAR_state_s3_bucket=$(aws s3 ls | grep eks-accelerator | awk '{print $3}')
      # Get DynamoDB Table
      - export TF_VAR_state_ddb_lock_table=$(aws dynamodb list-tables | jq -r '.TableNames[] | select("eks-accelerator-tf-lock")')
      # Get vpc
      - export TF_VAR_vpc_id=$(aws ec2 describe-vpcs --filters Name=tag:Name,Values="idp-admin" --query 'Vpcs[*].{VpcId:VpcId,Name:Tags[?Key==`Name`].Value|[0]}' --output text | awk '{print $2}')
      # Get vpc private subnets
      - export TF_VAR_vpc_private_subnets=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$TF_VAR_vpc_id" "Name=tag:Name,Values=*private*" --query "Subnets[*].SubnetId" --output json)
      # Get AZs
      - export TF_eks_cluster_private_az=$(aws ec2 describe-subnets --filters "Name=vpc-id,Values=$TF_VAR_vpc_id" --query 'Subnets[*].AvailabilityZone' --output json)
      # Get VPC CIDR
      - export TF_eks_cluster_vpc_cidr=$(aws ec2 describe-vpcs --vpc-ids $TF_VAR_vpc_id --query 'Vpcs[0].CidrBlock' --output text)
      
      # Clone Gitea repo
      - export GITEA_REPO=$GITEA_URL/giteaAdmin/terraform-eks.git
      - echo "Cloning Gitea repository..."
      - git -c http.sslVerify=false clone $GITEA_REPO
      - cd terraform-eks
      - chmod +x ./create-database.sh
      - ./create-database.sh
