apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: java-application
spec:
  components:
    - name: java-webservice 
      type: appmod-service
      properties:
        image:  public.ecr.aws/i8e1q7x5/appmod-demo:latest 
        image_name: java-app
        port: 8080
        # functionalGate:
        #   pause: "10s" 
        #   image: "public.ecr.aws/i8e1q7x5/appmod-javafunctest:latest"
        #   extraArgs: "red"
        # performanceGate:
        #   pause: "10s"
        #   image: "public.ecr.aws/i8e1q7x5/javaperftest:latest"
        #   extraArgs: "160"
      traits: 
        - type: path-based-ingress
          properties:
            domain: "*.amazonaws.com"
            rewritePath: "/java-app" 
            http:
              /java-app: 8080
        - type: aws-service-account
          properties:
            componentNamesForAccess:
              - java-s3
              - java-rds
            clusterRegion: us-west-2
            clusterName: idp-admin
    - name: java-s3
      type: s3-bucket
      properties:
        region: us-west-2
        name: java-bucket-12345
      traits:
        - type: component-iam-policy
          properties:
            service: s3
    - name: java-rds
      type: rds-cluster
      properties:
        region: us-west-2
        subnetIds:
          - subnet-0b19e7279169669f3
          - subnet-06ca846dc05c99f40
      traits:
        - type: component-iam-policy
          properties:
            service: rds
        
